import { Download } from 'lucide-react';

/**
 * SOAPNoteView Component
 * Displays formatted SOAP note (Subjective, Objective, Assessment, Plan)
 * Includes download functionality to export as text file
 * 
 * Props:
 * - soapNote: Object containing SOAP note sections
 */
function SOAPNoteView({ soapNote }) {
  if (!soapNote) return null;

  /**
   * Download SOAP note as text file
   * Formats the note as plain text and triggers browser download
   */
  const handleDownload = () => {
    // Format SOAP note as text
    const formatSection = (title, content) => {
      let text = `${title.toUpperCase()}\n${'='.repeat(60)}\n`;
      
      if (!content) {
        text += 'No information available\n\n';
        return text;
      }

      if (typeof content === 'string') {
        text += `${content}\n\n`;
        return text;
      }

      if (typeof content === 'object') {
        Object.entries(content).forEach(([key, value]) => {
          const label = key.split('_').map(word => 
            word.charAt(0).toUpperCase() + word.slice(1)
          ).join(' ');
          
          text += `${label}:\n`;
          
          if (Array.isArray(value)) {
            value.forEach(item => {
              text += `  - ${item}\n`;
            });
          } else {
            text += `  ${value}\n`;
          }
          text += '\n';
        });
      }

      return text;
    };

    // Build complete SOAP note text
    let soapText = '============================================================\n';
    soapText += 'SOAP NOTE - CLINICAL DOCUMENTATION\n';
    soapText += '============================================================\n\n';
    
    if (soapNote.generated_at) {
      soapText += `Generated: ${new Date(soapNote.generated_at).toLocaleString()}\n\n`;
    }

    soapText += formatSection('SUBJECTIVE', soapNote.subjective);
    soapText += formatSection('OBJECTIVE', soapNote.objective);
    soapText += formatSection('ASSESSMENT', soapNote.assessment);
    soapText += formatSection('PLAN', soapNote.plan);

    soapText += '============================================================\n';
    soapText += 'Generated by MediScribe AI\n';
    soapText += '============================================================\n';

    // Create blob and download
    const blob = new Blob([soapText], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    
    // Generate filename with timestamp
    const timestamp = new Date().toISOString().replace(/[:.]/g, '-').slice(0, -5);
    link.download = `soap-note-${timestamp}.txt`;
    
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
  };

  // Render a SOAP section with styled header
  const renderSection = (title, content, bgColor) => (
    <div className="mb-6">
      <div className={`${bgColor} px-4 py-2 rounded-t-lg`}>
        <h3 className="text-lg font-bold text-gray-800">{title}</h3>
      </div>
      <div className="bg-white border-2 border-t-0 border-gray-200 rounded-b-lg p-4">
        {renderSectionContent(content)}
      </div>
    </div>
  );

  // Render section content based on structure
  const renderSectionContent = (content) => {
    if (!content) return <p className="text-gray-500 italic">No information available</p>;

    if (typeof content === 'string') {
      return <p className="text-gray-700">{content}</p>;
    }

    if (typeof content === 'object') {
      return (
        <div className="space-y-3">
          {Object.entries(content).map(([key, value]) => (
            <div key={key}>
              <p className="font-semibold text-gray-800 mb-1">
                {key.split('_').map(word => word.charAt(0).toUpperCase() + word.slice(1)).join(' ')}:
              </p>
              {Array.isArray(value) ? (
                <ul className="list-disc list-inside text-gray-700 space-y-1">
                  {value.map((item, idx) => (
                    <li key={idx}>{item}</li>
                  ))}
                </ul>
              ) : (
                <p className="text-gray-700">{value}</p>
              )}
            </div>
          ))}
        </div>
      );
    }

    return null;
  };

  return (
    <div className="bg-white rounded-lg shadow-lg p-8">
      <div className="flex justify-between items-center mb-6">
        <h2 className="text-2xl font-bold text-gray-800">SOAP Note</h2>
        
        {/* Download Button */}
        <button
          onClick={handleDownload}
          className="flex items-center gap-2 px-4 py-2 bg-green-600 hover:bg-green-700 text-white font-semibold rounded-lg transition-colors"
        >
          <Download className="w-5 h-5" />
          Download as Text
        </button>
      </div>

      {/* Subjective Section */}
      {renderSection('Subjective', soapNote.subjective, 'bg-blue-100')}

      {/* Objective Section */}
      {renderSection('Objective', soapNote.objective, 'bg-green-100')}

      {/* Assessment Section */}
      {renderSection('Assessment', soapNote.assessment, 'bg-yellow-100')}

      {/* Plan Section */}
      {renderSection('Plan', soapNote.plan, 'bg-purple-100')}

      {/* Timestamp */}
      {soapNote.generated_at && (
        <div className="mt-6 text-sm text-gray-500 text-right">
          Generated: {new Date(soapNote.generated_at).toLocaleString()}
        </div>
      )}
    </div>
  );
}

export default SOAPNoteView;